# Generated by Django 5.2.1 on 2025-05-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makesure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
