# Generated by Django 5.2.1 on 2025-05-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makesure', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
